### ISSUE TITLE
PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by NiBoTe** [TheNorthMemory/wechatpay-axios-plugin#13]
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:105:29)
    at Function.sign (E:\work\ad\payment-applet\cloudfunctions\login\node_modules\_wechatpay-axios-plugin@0.4.4@wechatpay-axios-plugin\lib\rsa.js:60:23)
    at signer (E:\work\ad\payment-applet\cloudfunctions\login\node_modules\_wechatpay-axios-plugin@0.4.4@wechatpay-axios-plugin\lib\interceptor.js:71:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by TheNorthMemory** [comment]
@NiBoTe 实例化的时候，入参`privateKey` 需要是纯pem格式的`私钥证书`字符串或者`buffer`，文档上是示例用法，代指证书格式，应该是你实例化的时候，没给对`privateKey`格式的吧。

**Comment by cgx9** [comment]
同样的问题。该串在是从配置中心读的，java正常使用。

**Comment by TheNorthMemory** [comment]
> 同样的问题。该串在是从配置中心读的，java正常使用。

Java中读取的时候，应该是去掉了 `-----BEGIN CERTIFICATE-----` 以及 `-----END CERTIFICATE-----` 标识，纯base64的无换行符的字符串，这种方式的字符串在本类库中无法接入，建议尝试补齐上述信息再试试看。
