### ISSUE TITLE
调用Apiv3,h5下单直接报AssertionError [ERR_ASSERTION]: It's allowed time offset in ± 5 minutes, the response was on undefined, your's localtime on 1624555111.

### ISSUE THREAD

**Issue by LPJXLOVE** [TheNorthMemory/wechatpay-axios-plugin#30]
调用Apiv3,h5下单直接报AssertionError [ERR_ASSERTION]: It's allowed time offset in ± 5 minutes, the response was on undefined, your's localtime on 1624555111.

**Comment by TheNorthMemory** [comment]
问题与 #28 类同，服务端返回的异常错误处理，容我想一下怎么改进改进。

**Comment by victorykong** [comment]
@TheNorthMemory 大概需要多久解决？项目比较紧急
![image](https://user-images.githubusercontent.com/50655436/123432626-29395f00-d5fd-11eb-881e-20e171a0fa66.png)
![image](https://user-images.githubusercontent.com/50655436/123432761-466e2d80-d5fd-11eb-9b4b-fdd62cf11bdf.png)

**Comment by TheNorthMemory** [comment]
应该是你的`notify_url`是非法地址，服务端检测出来失败了，这里有些问题就是，对于非正常业务参数服务端检测失败的，没有给返回4个验签参数，很不洁癖；你先试试给个正确地址，下单看看

**Comment by TheNorthMemory** [comment]
另外，`time_expire: new Date( (+new Date) + 5*60*1000 ),` 这么写，服务端就支持的，不用再偏移`+08:00`时区的

**Comment by victorykong** [comment]
@TheNorthMemory  在服务器上修改后，仍然报这个错误，麻烦了
![image](https://user-images.githubusercontent.com/50655436/123441076-08c1d280-d606-11eb-8861-d9d7a535561e.png)
![image](https://user-images.githubusercontent.com/50655436/123441140-1b3c0c00-d606-11eb-8276-3ffe631c0a0f.png)
![image](https://user-images.githubusercontent.com/50655436/123441227-30189f80-d606-11eb-81a4-44618f9c08aa.png)

**Comment by TheNorthMemory** [comment]
@victorykong 你最后这张图上，看着是请求沙箱环境，`v3`暂时还没有沙箱环境，在你`开发`及`正式`环境，要把 `baseURL` 去掉。

**Comment by victorykong** [comment]
2021-06-26 14:43:39,380 INFO 2157616 [-/183.17.127.248/-/252ms POST /v1/pay/wx/h5] err TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareAsymmetricKey (internal/crypto/keys.js:299:9)
    at preparePublicOrPrivateKey (internal/crypto/keys.js:312:10)
    at Verify.verify (internal/crypto/sig.js:175:7)
    at Function.verify (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/rsa.js:77:66)
    at verifier (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/decorator.js:140:13)
    at transform (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:16:12)
    at Object.forEach (/opt/script-legend-backend/node_modules/axios/lib/utils.js:247:10)
    at transformData (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:15:9)
    at onAdapterRejection (/opt/script-legend-backend/node_modules/axios/lib/core/dispatchRequest.js:69:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by victorykong** [comment]
@TheNorthMemory 
请问这个是什么问题？

**Comment by TheNorthMemory** [comment]
`Rsa.verify` 验签逻辑失败，`Received undefined`，你没给对初始化参数 `certs`

**Comment by victorykong** [comment]
我初始化的时候 有传递了这个参数哦

**Comment by victorykong** [comment]
2021-06-26 15:28:15,784 INFO 2166336 [-/183.17.127.248/-/139ms POST /v1/pay/wx/h5] {
  mchid: '161110*******',
  serial: '3F6A1EBF27D9A7F****',
  privateKey: '-----BEGIN PRIVATE KEY-----\n' +
    '*******/ICXR9\n' +
    '*******+mOTKpcEo60nyDaAN1w93enxAv/eRXGSI/xEsojyXR0Mu0YHq5EB+q\n' +
    '*******/1+CLQyw0w/ElgLV7GFJgwgr91YIubWQoN+cYENM3v5JE\n' +
    '*******+Z9JrwFizpmZ6\n' +
    '*******/wEzIf8evC3bJBGaz6I73WqkUQ7hbbtp4wZwRtgpR3O8g+I22LIjEe6NqBlX\n' +
    '*******/ZZv/Jo9ckvMlDZfaWB3mU6mOUqM51hYFPJ1dajwWNrYzEm0sK6\n' +
    '*******+xJTDAgMBAAECggEBAKLpTvIrnaCuFP8+whUhOtl1UyPNajEXpOZFBVyztJQH\n' +
    '*******\n' +
    '*******/cFImtZPEbOfgSrhV1kx9b/tG0owFt6NoT+c7Xp+BaPLz2\n' +
    '*******+NMVYq7vhfEH0tgZ5S6UVpDvRbplmu9xcIX0wy10GDrEjAfZ+7fNFKW\n' +
    '*******/+JPZTIlpKUWsJ+uroo9MPvTPhtzIygu8N09DuRsz9xAFNb4+CNRUt5itN\n' +
    '*******/8zu0Qjdj/PKOImKr7QkQUeE7pFPxQ+yX7VK+HbqdECgYEA4DkW08YQd5rzZPyE\n' +
    '*******+36vwiTnWTYqR++tyQjHa4yAyfmDZFoAkvViPks250omFGnGA7\n' +
    '*******+hGrenQNhb4UHTfbAjlDdYjIQCwW1LbKb0oxj1+oO\n' +
    '*******\n' +
    '*******+j9H7m+OzNfYPGOVdDavO28SMshhgsj9YwhG3CGekVCDd\n' +
    '*******/plZ8YMS8TtDOA8yfXGFUYCu5rhpRMl2ngN+hcmC3m\n' +
    '*******+4IhKdlYPk0W5Emg4LET5DQjQuOL9eVCK0Z1FGjlmFu2ssnE\n' +
    '*******iCHqruB8ZhT5Wiud+J3oXwpKbQIBo+9NipWan/v8cBgz66PLkJnHINvC0MfRI4j\n' +
    '*******+oCkQ3A9zVhXeqWpC0qh23y0W1yIWh7lh/xdz5NQmPghWyMMEI0QKBgBUz\n' +
    '*******+1Ju4o9PoOnRARKi1kctqeXb/44PVEz3sdIJBrKmiN9UnH4Cn0aoBKnM\n' +
    '*******/2GXqg7QDV7JIKcgaSMgkqn3StX6oWt3JBArTto8EswZB3tWbwipo4\n' +
    '*******/uMCYouvjiktzQsNYgewDKiV7N3EwxAoGBALAm3Tu+uzN2Lwht0r7z\n' +
    '*******/PX02ptt4KgzjJiRNd3yTVpblSxJOV+bQa6z+QqPHI\n' +
    '*******+wuV2YEL2Nisqw6p+73n1vIw0q1eMtjlt/K0xZOkENXoLimcOBa+gqI\n' +
    '*******/ExA10LRUvJ\n' +
    '-----END PRIVATE KEY-----\n',
  certs: {
    '3F6A1EBF27D9A7F****': '-----BEGIN CERTIFICATE-----\n' +
      '**********/DCCAuSgAwIBAgIUP2oevyfZp/o3DjVwvq8e7lLVd2QwDQYJKoZIhvcNAQEL\n' +
      '**********\n' +
      '**********\n' +
      '**********\n' +
      '**********+h5ZWG5oi357O757ufMTkwNwYDVQQL\n' +
      '**********\n' +
      '**********\n' +
      '**********/hh78gJdH1qABi8xqjQL6Y5MqlwSjrSfINo\n' +
      '**********/95FcZIj/ESyiPJdHQy7RgerkQH6rhlO1OZp5prVMRaIuN93/X4ItD\n' +
      '**********/kkRLkOSTbZP3xiPg6Y9CSZbWZxXQ\n' +
      '**********/ATMh/x68LdskEZrPojvd\n' +
      '**********/8mj1yS8y\n' +
      '**********/MAkG\n' +
      '**********\n' +
      '**********/Q0E9MUJENDIyMEU1MERC\n' +
      '**********\n' +
      '**********\n' +
      '**********/r6OsmVguykMC8WS69iSYCTmfFXvUCXDbROf+pGUTLvA+RMMsO8Z\n' +
      '**********+MQeHhmQjMVHkSv3LwJqUAKY++pJ8j4lVsYo7ZeDZpz02OHciDZ5\n' +
      '**********/Skooclz3DGjD8UoYYBSAkxz2A1haF+70+R6A3J3rzWSzmsGQlxEN\n' +
      '**********+4hR6YXsuSbbnR8DeN+hPzzSG/PPmV/p+X3NGWUqu2vWO+Ya2BFime6DbS2E56p\n' +
      '**********/WL9Gztyjh0wY/7e/UNOg==\n' +
      '-----END CERTIFICATE-----\n'
  },
  secret: 'scr******nd8r********8',
  maxRedirects: 0
}
2021-06-26 15:28:15,805 INFO 2166336 [-/183.17.127.248/-/160ms POST /v1/pay/wx/h5] @infoReqResLogger res > {"body":{"message":"","error_code":0,"success":true,"data":{}},"status":200,"message":"OK","length":54,"type":"application/json"}
2021-06-26 15:28:15,805 INFO 2166336 [-/183.17.127.248/-/160ms POST /v1/pay/wx/h5] @infoReqResLogger time sum > { ms: 157, s: 0.157 }
2021-06-26 15:28:15,910 INFO 2166336 [-/183.17.127.248/-/265ms POST /v1/pay/wx/h5] err TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareAsymmetricKey (internal/crypto/keys.js:299:9)
    at preparePublicOrPrivateKey (internal/crypto/keys.js:312:10)
    at Verify.verify (internal/crypto/sig.js:175:7)
    at Function.verify (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/rsa.js:77:66)
    at verifier (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/decorator.js:140:13)
    at transform (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:16:12)
    at Object.forEach (/opt/script-legend-backend/node_modules/axios/lib/utils.js:247:10)
    at transformData (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:15:9)
    at onAdapterRejection (/opt/script-legend-backend/node_modules/axios/lib/core/dispatchRequest.js:69:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by victorykong** [comment]
`2021-06-26 15:28:15,784 INFO 2166336 [-/183.17.127.248/-/139ms POST /v1/pay/wx/h5] {
  mchid: '161110*******',
  serial: '3F6A1EBF27D9A7F****',
  privateKey: '-----BEGIN PRIVATE KEY-----\n' +
    '*******/ICXR9\n' +
    '*******+mOTKpcEo60nyDaAN1w93enxAv/eRXGSI/xEsojyXR0Mu0YHq5EB+q\n' +
    '*******/1+CLQyw0w/ElgLV7GFJgwgr91YIubWQoN+cYENM3v5JE\n' +
    '*******+Z9JrwFizpmZ6\n' +
    '*******/wEzIf8evC3bJBGaz6I73WqkUQ7hbbtp4wZwRtgpR3O8g+I22LIjEe6NqBlX\n' +
    '*******/ZZv/Jo9ckvMlDZfaWB3mU6mOUqM51hYFPJ1dajwWNrYzEm0sK6\n' +
    '*******+xJTDAgMBAAECggEBAKLpTvIrnaCuFP8+whUhOtl1UyPNajEXpOZFBVyztJQH\n' +
    '*******\n' +
    '*******/cFImtZPEbOfgSrhV1kx9b/tG0owFt6NoT+c7Xp+BaPLz2\n' +
    '*******+NMVYq7vhfEH0tgZ5S6UVpDvRbplmu9xcIX0wy10GDrEjAfZ+7fNFKW\n' +
    '*******/+JPZTIlpKUWsJ+uroo9MPvTPhtzIygu8N09DuRsz9xAFNb4+CNRUt5itN\n' +
    '*******/8zu0Qjdj/PKOImKr7QkQUeE7pFPxQ+yX7VK+HbqdECgYEA4DkW08YQd5rzZPyE\n' +
    '*******+36vwiTnWTYqR++tyQjHa4yAyfmDZFoAkvViPks250omFGnGA7\n' +
    '*******+hGrenQNhb4UHTfbAjlDdYjIQCwW1LbKb0oxj1+oO\n' +
    '*******\n' +
    '*******+j9H7m+OzNfYPGOVdDavO28SMshhgsj9YwhG3CGekVCDd\n' +
    '*******/plZ8YMS8TtDOA8yfXGFUYCu5rhpRMl2ngN+hcmC3m\n' +
    '*******+4IhKdlYPk0W5Emg4LET5DQjQuOL9eVCK0Z1FGjlmFu2ssnE\n' +
    '*******iCHqruB8ZhT5Wiud+J3oXwpKbQIBo+9NipWan/v8cBgz66PLkJnHINvC0MfRI4j\n' +
    '*******+oCkQ3A9zVhXeqWpC0qh23y0W1yIWh7lh/xdz5NQmPghWyMMEI0QKBgBUz\n' +
    '*******+1Ju4o9PoOnRARKi1kctqeXb/44PVEz3sdIJBrKmiN9UnH4Cn0aoBKnM\n' +
    '*******/2GXqg7QDV7JIKcgaSMgkqn3StX6oWt3JBArTto8EswZB3tWbwipo4\n' +
    '*******/uMCYouvjiktzQsNYgewDKiV7N3EwxAoGBALAm3Tu+uzN2Lwht0r7z\n' +
    '*******/PX02ptt4KgzjJiRNd3yTVpblSxJOV+bQa6z+QqPHI\n' +
    '*******+wuV2YEL2Nisqw6p+73n1vIw0q1eMtjlt/K0xZOkENXoLimcOBa+gqI\n' +
    '*******/ExA10LRUvJ\n' +
    '-----END PRIVATE KEY-----\n',
  certs: {
    '3F6A1EBF27D9A7F****': '-----BEGIN CERTIFICATE-----\n' +
      '**********/DCCAuSgAwIBAgIUP2oevyfZp/o3DjVwvq8e7lLVd2QwDQYJKoZIhvcNAQEL\n' +
      '**********\n' +
      '**********\n' +
      '**********\n' +
      '**********+h5ZWG5oi357O757ufMTkwNwYDVQQL\n' +
      '**********\n' +
      '**********\n' +
      '**********/hh78gJdH1qABi8xqjQL6Y5MqlwSjrSfINo\n' +
      '**********/95FcZIj/ESyiPJdHQy7RgerkQH6rhlO1OZp5prVMRaIuN93/X4ItD\n' +
      '**********/kkRLkOSTbZP3xiPg6Y9CSZbWZxXQ\n' +
      '**********/ATMh/x68LdskEZrPojvd\n' +
      '**********/8mj1yS8y\n' +
      '**********/MAkG\n' +
      '**********\n' +
      '**********/Q0E9MUJENDIyMEU1MERC\n' +
      '**********\n' +
      '**********\n' +
      '**********/r6OsmVguykMC8WS69iSYCTmfFXvUCXDbROf+pGUTLvA+RMMsO8Z\n' +
      '**********+MQeHhmQjMVHkSv3LwJqUAKY++pJ8j4lVsYo7ZeDZpz02OHciDZ5\n' +
      '**********/Skooclz3DGjD8UoYYBSAkxz2A1haF+70+R6A3J3rzWSzmsGQlxEN\n' +
      '**********+4hR6YXsuSbbnR8DeN+hPzzSG/PPmV/p+X3NGWUqu2vWO+Ya2BFime6DbS2E56p\n' +
      '**********/WL9Gztyjh0wY/7e/UNOg==\n' +
      '-----END CERTIFICATE-----\n'
  },
  secret: 'scr******nd8r********8',
  maxRedirects: 0
}
2021-06-26 15:28:15,805 INFO 2166336 [-/183.17.127.248/-/160ms POST /v1/pay/wx/h5] @infoReqResLogger res > {"body":{"message":"","error_code":0,"success":true,"data":{}},"status":200,"message":"OK","length":54,"type":"application/json"}
2021-06-26 15:28:15,805 INFO 2166336 [-/183.17.127.248/-/160ms POST /v1/pay/wx/h5] @infoReqResLogger time sum > { ms: 157, s: 0.157 }
2021-06-26 15:28:15,910 INFO 2166336 [-/183.17.127.248/-/265ms POST /v1/pay/wx/h5] err TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareAsymmetricKey (internal/crypto/keys.js:299:9)
    at preparePublicOrPrivateKey (internal/crypto/keys.js:312:10)
    at Verify.verify (internal/crypto/sig.js:175:7)
    at Function.verify (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/rsa.js:77:66)
    at verifier (/opt/script-legend-backend/node_modules/wechatpay-axios-plugin/lib/decorator.js:140:13)
    at transform (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:16:12)
    at Object.forEach (/opt/script-legend-backend/node_modules/axios/lib/utils.js:247:10)
    at transformData (/opt/script-legend-backend/node_modules/axios/lib/core/transformData.js:15:9)
    at onAdapterRejection (/opt/script-legend-backend/node_modules/axios/lib/core/dispatchRequest.js:69:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by victorykong** [comment]
@TheNorthMemory

**Comment by TheNorthMemory** [comment]
`certs: { '3F6A1EBF27D9A7F****'` 传错了，要传`平台证书及序列号`，你传的是`商户证书及序列号`，平台证书要通过下载器下载 @victorykong

**Comment by victorykong** [comment]
@TheNorthMemory 微信支付官网文档上，没有看到有这一步，我理解在我的微信支付中，没有发钱给用户的场景，仅仅只是收款，是不是这个参数不需要？https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_6_1.shtml
