### ISSUE TITLE
有的机器验证返回签名报错

### ISSUE THREAD

**Issue by shengxq** [TheNorthMemory/wechatpay-axios-plugin#42]
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at prepareAsymmetricKey (node:internal/crypto/keys:570:9)
    at preparePublicOrPrivateKey (node:internal/crypto/keys:581:10)
    at Verify.verify (node:internal/crypto/sig:217:7)
    at Function.verify (/root/payapi2/node_modules/wechatpay-axios-plugin/lib/rsa.js:78:23)
    at verifier (/root/payapi2/node_modules/wechatpay-axios-plugin/lib/interceptor.js:115:11)
    at runMicrotasks (<anonymous>)

奇怪的是  有的机器没有问题,有的有问题
certs[serial]=wechatpayPublicCert
const client = wxp(instance, {
                mchid: global.微信服务商Id,
                serial: serial,
                privateKey: merchantPrivateKey,
                certs: certs
            });

serial  变量是传入的参数
interceptor.js 文件第98行 有定义变量const serial = response.headers[`wechatpay-serial`]
这个是不是有冲突

在113行 应该是检查返回数据的签名
certs[serial]  这个是获取不到内容的
不知道出错的原因是不是这个

**Comment by shengxq** [comment]
已经查明了 certs 要去传的是 微信支付平台证书
且这个证书是需要定期更换的

**Comment by TheNorthMemory** [comment]
是的，证书每5年一换，按官方开发建议，定期拉取更新即可。

https://pay.weixin.qq.com/wiki/doc/apiv3/apis/wechatpay5_1.shtml

## 注意事项

如果自行实现验证平台签名逻辑的话，需要注意以下事项:

- 程序实现定期更新平台证书的逻辑，不要硬编码验证应答消息签名的平台证书
- 定期调用该接口，间隔时间小于12 小时
- 加密请求消息中的敏感信息时，使用最新的平台证书（即：证书启用时间较晚的证书）
